# Generated by Django 5.1.2 on 2024-12-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='value_sgr',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='value_sgr'),
        ),
    ]
