# Generated by Django 5.1.2 on 2024-11-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='nit',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='nit'),
        ),
    ]
