# Generated by Django 5.1.2 on 2024-12-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
    ]
