# Generated by Django 5.1.2 on 2024-12-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activity_end_date_remove_activity_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end_date'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start_date'),
        ),
    ]
