# Generated by Django 5.1.2 on 2024-12-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_end_date_activity_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='state',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='state'),
        ),
    ]
