# Generated by Django 5.1.2 on 2024-11-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='value')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end_date')),
                ('file_budget_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='file_budget_url')),
                ('file_activities_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='file_activities_url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['id'],
            },
        ),
    ]
