# Generated by Django 5.1.2 on 2024-12-05 20:46

import core.projects.helpers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('value', models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='value')),
                ('start_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='start_date')),
                ('end_date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='end_date')),
                ('file_budget', models.FileField(null=True, upload_to=core.projects.helpers.RenameFileWithProjectID('budgets'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='file_budget')),
                ('file_activities', models.FileField(null=True, upload_to=core.projects.helpers.RenameFileWithProjectID('activities'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='file_activities')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.entity')),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['id'],
            },
        ),
    ]
