# Generated by Django 5.1.2 on 2024-12-04 20:16

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file_activities_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='file_budget_url',
        ),
        migrations.AddField(
            model_name='project',
            name='file_activities',
            field=models.FileField(null=True, upload_to='projects/activities/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='file_activities'),
        ),
        migrations.AddField(
            model_name='project',
            name='file_budget',
            field=models.FileField(null=True, upload_to='projects/budgets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])], verbose_name='file_budget'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='start_date'),
        ),
    ]
