# Generated by Django 5.1.2 on 2024-12-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=18, verbose_name='value'),
        ),
    ]
