# Generated by Django 5.1.2 on 2024-12-05 03:10

import core.projects.helpers
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_project_file_activities_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="file_activities",
            field=models.FileField(
                null=True,
                upload_to=core.projects.helpers.RenameFileWithProjectID("activities"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xlsx"]
                    )
                ],
                verbose_name="file_activities",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="file_budget",
            field=models.FileField(
                null=True,
                upload_to=core.projects.helpers.RenameFileWithProjectID("budgets"),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["xlsx"]
                    )
                ],
                verbose_name="file_budget",
            ),
        ),
    ]
