# Generated by Django 5.1.2 on 2024-12-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_file_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='value'),
        ),
    ]
