# Generated by Django 5.1.2 on 2024-12-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
    ]
