# Generated by Django 5.1.2 on 2024-12-12 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
    ]
