# Generated by Django 5.1.2 on 2024-11-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterpart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value_species', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='value_species')),
                ('value_chash', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='value_chash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rubro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubros.rubro')),
            ],
            options={
                'db_table': 'counterparts',
                'ordering': ['id'],
            },
        ),
    ]
