# Generated by Django 5.1.2 on 2024-12-17 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterparts', '0002_remove_counterpart_rubro_counterpart_project_and_more'),
        ('projects', '0006_remove_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterpart',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
