# Generated by Django 5.1.2 on 2024-11-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='origin')),
                ('destination', models.CharField(blank=True, max_length=100, null=True, verbose_name='destination')),
                ('transport', models.CharField(blank=True, max_length=100, null=True, verbose_name='transport')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('cant_persons', models.IntegerField(blank=True, null=True, verbose_name='cant_persons')),
                ('cant_days', models.IntegerField(blank=True, null=True, verbose_name='cant_days')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rubro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubros.rubro')),
            ],
            options={
                'db_table': 'travels',
                'ordering': ['id'],
            },
        ),
    ]
