# Generated by Django 5.1.2 on 2024-12-09 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdps', '0002_remove_cdps_document_url'),
        ('movements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='contract',
        ),
        migrations.AddField(
            model_name='movement',
            name='cdp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdps.cdps'),
        ),
    ]
