# Generated by Django 5.1.2 on 2024-12-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0002_remove_movement_contract_movement_cdp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description'),
        ),
    ]
