# Generated by Django 5.1.2 on 2024-12-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movements', '0003_alter_movement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='amount'),
        ),
    ]
