# Generated by Django 5.1.2 on 2024-12-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counterpartExecution', '0002_initial'),
        ('movementsCounterpart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementsCounterparts',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('I', 'Ingresos'), ('G', 'Gastos')], default='I', max_length=1)),
                ('temp_field', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('counterpart_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterpartExecution.counterpartexecution')),
            ],
            options={
                'db_table': 'movements_counterparts',
                'ordering': ['id'],
            },
        ),
    ]
