# Generated by Django 5.1.2 on 2024-12-18 20:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movementsCounterpart', '0003_remove_movementscounterparts_temp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementscounterparts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
