# Generated by Django 5.1.2 on 2024-11-27 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='description')),
                ('justificacion', models.TextField(blank=True, max_length=150, null=True, verbose_name='justificacion')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit_value')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total_value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('rubro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubros.rubro')),
            ],
            options={
                'db_table': 'items',
                'ordering': ['id'],
            },
        ),
    ]
