# Generated by Django 5.1.2 on 2024-12-18 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_activity_duration'),
        ('counterpartExecution', '0001_initial'),
        ('counterparts', '0003_alter_counterpart_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterpartExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='number')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('expedition_date', models.DateField(blank=True, null=True, verbose_name='expedition_date')),
                ('is_generated', models.BooleanField(default=False, verbose_name='is_generated')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='is_canceled')),
                ('temp_field', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activity')),
                ('counterpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='counterparts.counterpart')),
            ],
            options={
                'db_table': 'counterpart_executions',
                'ordering': ['id'],
            },
        ),
    ]
