# Generated by Django 5.1.2 on 2024-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counterpartExecution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterpartexecution',
            name='type',
        ),
        migrations.AddField(
            model_name='counterpartexecution',
            name='expedition_date',
            field=models.DateField(blank=True, null=True, verbose_name='expedition_date'),
        ),
        migrations.AddField(
            model_name='counterpartexecution',
            name='is_canceled',
            field=models.BooleanField(default=False, verbose_name='is_canceled'),
        ),
        migrations.AddField(
            model_name='counterpartexecution',
            name='is_generated',
            field=models.BooleanField(default=False, verbose_name='is_generated'),
        ),
        migrations.AddField(
            model_name='counterpartexecution',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='number'),
        ),
    ]
