# Generated by Django 5.1.2 on 2024-12-05 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='job_title')),
                ('dedication', models.CharField(blank=True, max_length=100, null=True, verbose_name='dedication')),
                ('weeks', models.CharField(blank=True, max_length=100, null=True, verbose_name='weeks')),
                ('fees', models.CharField(blank=True, max_length=100, null=True, verbose_name='fees')),
                ('value_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='value_hour')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubros.rubro')),
            ],
            options={
                'db_table': 'persons',
                'ordering': ['id'],
            },
        ),
    ]
