# Generated by Django 5.1.2 on 2024-11-24 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='rubro_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubros.rubro'),
        ),
    ]
