# Generated by Django 5.1.2 on 2024-11-28 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='rubro_id',
            new_name='rubro',
        ),
    ]
