# Generated by Django 5.1.2 on 2024-12-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_num',
            field=models.IntegerField(default=0, verbose_name='task_num'),
        ),
    ]
