# Generated by Django 5.1.2 on 2024-12-05 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_end_date_activity_start_date'),
        ('tasks', '0003_task_end_date_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.activity'),
        ),
    ]
