# Generated by Django 5.1.2 on 2024-12-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='name'),
        ),
    ]
