# Generated by Django 5.1.2 on 2024-11-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='number')),
                ('expedition_date', models.DateField(blank=True, null=True, verbose_name='expedition_date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_generated', models.BooleanField(default=False, verbose_name='is_generated')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='is_canceled')),
                ('document', models.CharField(blank=True, max_length=150, null=True, verbose_name='document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cdps',
                'ordering': ['id'],
            },
        ),
    ]
