# Generated by Django 5.1.2 on 2024-11-27 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='number')),
                ('expedition_date', models.DateField(blank=True, null=True, verbose_name='expedition_date')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_generated', models.BooleanField(default=False, verbose_name='is_generated')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='is_canceled')),
                ('document_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='document_url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rubro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubros.rubro')),
            ],
            options={
                'db_table': 'cdps',
                'ordering': ['id'],
            },
        ),
    ]
