# Generated by Django 5.1.2 on 2024-11-25 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdps', '0001_initial'),
        ('rubros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdps',
            name='document',
        ),
        migrations.AddField(
            model_name='cdps',
            name='document_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='document_url'),
        ),
        migrations.AddField(
            model_name='cdps',
            name='rubro_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubros.rubro'),
        ),
    ]
